"""Generate the bounded CiA 418 reference OD artifacts."""
from pathlib import Path
import sys

from cia418_catalog import ARRAYS, RECORDS, SCALARS

ROOT = Path(__file__).resolve().parents[1]
GENERATED = ROOT / "Generated"
OD_DIR = ROOT / "ObjectDictionary"


def c_default(ctype):
    return "0"


def generate_header():
    lines = [
        "/* Generated by scripts/generate_cia418_od.py; do not edit. */",
        "#ifndef CIA418_OD_H",
        "#define CIA418_OD_H",
        "#include <stdint.h>",
        "",
        "typedef struct {",
    ]
    for index, ident, ctype, *_ in SCALARS:
        lines.append(f"    {ctype} x{index:04X}_{ident};")
    for index, ident, fields in RECORDS:
        lines.append("    struct {")
        for _sub, field, ctype, *_ in fields:
            lines.append(f"        {ctype} {field};")
        lines.append(f"    }} x{index:04X}_{ident};")
    for index, ident, ctype, _eds, _access, count in ARRAYS:
        lines.append(f"    {ctype} x{index:04X}_{ident}[{count + 1}];")
    lines.extend([
        "} CIA418_OD_APP_t;",
        "",
        "typedef struct {",
        "    uint16_t index;",
        "    uint8_t sub_count;",
        "    uint8_t data_length;",
        "    uint8_t writable;",
        "} CIA418_OD_ENTRY_t;",
        "",
        "extern CIA418_OD_APP_t CIA418_OD_APP;",
        "extern const CIA418_OD_ENTRY_t CIA418_OD_ENTRIES[];",
        "extern const uint16_t CIA418_OD_ENTRY_COUNT;",
        "",
        "#endif",
        "",
    ])
    return "\n".join(lines)


def generate_source():
    lines = [
        "/* Generated by scripts/generate_cia418_od.py; do not edit. */",
        '#include "cia418_OD.h"',
        "",
        "CIA418_OD_APP_t CIA418_OD_APP = {",
    ]
    for index, ident, *_ in SCALARS:
        lines.append(f"    .x{index:04X}_{ident} = 0,")
    for index, ident, fields in RECORDS:
        lines.append(f"    .x{index:04X}_{ident} = {{0}},")
    for index, ident, *_ in ARRAYS:
        lines.append(f"    .x{index:04X}_{ident} = {{0}},")
    lines.extend(["};", "", "const CIA418_OD_ENTRY_t CIA418_OD_ENTRIES[] = {"])
    for index, _ident, ctype, _eds, access, _category in SCALARS:
        length = {"uint8_t": 1, "int16_t": 2, "uint16_t": 2, "uint32_t": 4}[ctype]
        lines.append(f"    {{0x{index:04X}, 1, {length}, {1 if access == 'rw' else 0}}},")
    for index, _ident, fields in RECORDS:
        lines.append(f"    {{0x{index:04X}, {len(fields) + 1}, 0, 0}},")
    for index, _ident, ctype, _eds, access, count in ARRAYS:
        length = {"uint16_t": 2, "uint32_t": 4}[ctype]
        lines.append(f"    {{0x{index:04X}, {count + 1}, {length}, {1 if access == 'rw' else 0}}},")
    lines.extend([
        "};",
        "",
        "const uint16_t CIA418_OD_ENTRY_COUNT =",
        "    (uint16_t)(sizeof(CIA418_OD_ENTRIES) / sizeof(CIA418_OD_ENTRIES[0]));",
        "",
    ])
    return "\n".join(lines)


def generate_eds():
    lines = [
        "[FileInfo]",
        "FileName=stm32f767_cia418_reference.eds",
        "FileVersion=1",
        "EDSVersion=4.0",
        "",
        "[DeviceInfo]",
        "VendorName=STM32F767 CANopen Reference",
        "ProductName=CiA 418 Battery Module Personality",
        "",
        "[MandatoryObjects]",
        f"SupportedObjects={len({0x1000, 0x1001, 0x1018} | {0x6000, 0x6001, 0x6010, 0x6020})}",
        "1=0x1000",
        "2=0x1001",
        "3=0x1018",
        "4=0x6000",
        "5=0x6001",
        "6=0x6010",
        "7=0x6020",
        "",
        "[OptionalObjects]",
        f"SupportedObjects={len(SCALARS) + len(RECORDS) + len(ARRAYS) - 4}",
    ]
    position = 1
    for index, *_ in SCALARS + RECORDS + ARRAYS:
        if index in {0x6000, 0x6001, 0x6010, 0x6020}:
            continue
        lines.append(f"{position}=0x{index:04X}")
        position += 1
    lines.append("")
    return "\n".join(lines)


def main():
    (GENERATED / "cia418_OD.h").write_text(generate_header())
    (GENERATED / "cia418_OD.c").write_text(generate_source())
    (OD_DIR / "stm32f767_cia418_reference.eds").write_text(generate_eds())


if __name__ == "__main__":
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    main()
